* Purpose
  This is a tetris clone done from scratch to gain some experience
  with the [[https://ebitengine.org/][ebiten]] engine.

  There are a handful of known bugs not yet fixed as of 2023-03-22.

* Getting Started
  Use the =run.sh= script to build and run the project.  It requires a
  Mac or Linux machine with Go 1.19 installed and setup.  (It will
  likely run on Windows as well, it is just untested on that Platform)

  Add =$GOPATH/bin= to your path for convenience.

  #+begin_src shell
    export PATH="$GOPATH/bin:$PATH"
  #+end_src

  Then in a terminal, navigate to this directory and run the following
  command:

  #+begin_src shell
    go get gopkg.in/yaml.v3
    go mod tidy && ./run.sh build && ebiten-01 new-game
  #+end_src

  That should pull down the project dependencies, write the built
  executable to =$GOPATH/bin/= and then execute the command.

* Game Play
  Use =j= to move =left=.

  Use =l= to ove =right=.

  Use =space= to =rotate= the peice.

  Use =k= to =drop= the peice.

  Use =p= to =pause= the game.

  Use =q= to =quit= the game.

  Use =r= to =reset= peice, sending the falling peice to the top, but only
  before it's been placed in the stack

  Use =0= will restart the game with score of zero, level one and clears the board.
